Repository zenn-dev/zenn-mde, pull requests merged in 2020-11, with the labels that each got.

#17 Hotfix/1.2.3
  demo/index.tsx
  package.json
  src/components/Editor.tsx
  src/components/Preview.tsx
Labels: release

#18 chore(export): add more exports
  README.md
  package.json
  src/hooks/index.tsx
  src/index.ts
  src/types/index.ts
  src/types/targets.ts
Labels: chore

#19 Release/1.3.0
  README.md
  demo/index.tsx
  package-lock.json
  package.json
  src/components/Editor.tsx
  src/components/Preview.tsx
  src/components/Textarea.tsx
Labels: release

#20 Placeholderをpropsとして追加
  package.json
  src/components/Editor.tsx
  src/components/Textarea.tsx
Labels: chore

#21 chore: bumping version 1.3.1
  package.json
  src/components/Editor.tsx
  src/components/Textarea.tsx
Labels: release

#22 textareaにvalueを渡しても更新されない問題を修正
  demo/index.tsx
  src/components/Textarea.tsx
Labels: bugfix

#23 chore: bumping version
  package.json
Labels: release

#24 Fix: orderListおよびbullestListで何も入力がない場合にEnterが入力された場合の挙動を修正
  package.json
  src/commands/bulletList.ts
  src/commands/orderedList.ts
Labels: bugfix

#25 Fix: windows IME problems
  demo/index.tsx
  package.json
  src/components/Textarea.tsx
  src/hooks/index.tsx
  src/types/commands.ts
Labels: bugfix

#27 fix: bulletlist orderedlist composing
  package.json
  src/commands/bulletList.ts
  src/commands/orderedList.ts
Labels: bugfix

#28 feat: autosized textarea
  package-lock.json
  package.json
  src/components/Textarea.tsx
Labels: enhancement

#29 Feature: コマンドをもう少し使いやすく
  demo/index.tsx
  src/commands/bulletList.ts
  src/components/Editor.tsx
  src/components/Textarea.tsx
  src/index.ts
  yarn.lock
Labels: enhancement

#30 Release/1.4.0
  demo/index.tsx
  package-lock.json
  package.json
  src/commands/bulletList.ts
  src/components/Editor.tsx
  src/components/Textarea.tsx
  src/index.ts
  yarn.lock
Labels: release

#32 fix: list breaks on save shortcut
  src/commands/bulletList.ts
  src/commands/orderedList.ts
Labels: fix

#33 Hotfix/1.4.1
  package.json
  src/commands/bulletList.ts
  src/commands/orderedList.ts
  src/components/Textarea.tsx
Labels: release

#34 feat(command): focusのlastオプションを用意
  demo/index.tsx
  src/components/Textarea.tsx
  src/hooks/index.tsx
Labels: enhancement

#35 Hotfix/1.4.2
  demo/index.tsx
  package.json
  src/components/Textarea.tsx
  src/hooks/index.tsx
Labels: release
